#!/bin/bash
# ============ ENV VARS ================================
cd /root
export LANG=en_US.UTF-8
export HOME=/root
export SHELL=/bin/bash
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
export MAIL=/var/mail/root
export USER=root

source /etc/profile

# ============ PRINT MESSAGE ===========================
# Colors
BLACK=$'\033[30;01m'
RED=$'\033[31;01m'
GREEN=$'\033[32;01m'
YELW=$'\033[33;01m'
BLUE=$'\033[34;01m'
PURP=$'\033[35;01m'
CYAN=$'\033[36;01m'
WHITE=$'\033[37;01m'
GREY=$'\033[37;00m'
OFF=$'\033[0m'

# fix broken console with utf8 in the alternative-kernels
echo -n -e '\033%G'
kbd_mode -u

LINES=$(stty size|cut -d" " -f1)
fbecho(){
  [ $LINES -ge 28 ] && echo
}

VERSION="7.0"
OS_LOGO="/etc/funtoo.ascii"
OS_LOGO_SMALL="/etc/funtoo_small.ascii"
LOCAL_RESOLUTION="$(fbset -s | grep mode -w | awk '{print $2}' | sed s,'\"',,g | cut -dx -f1)"

if [ ${LOCAL_RESOLUTION} -le 1440 ];then
	OS_LOGO_SET="${OS_LOGO_SMALL}"
else
	OS_LOGO_SET="${OS_LOGO}"
fi

sbctl status &> /dev/null
if [ "$?" -ne 0 ]; then
	MODE_HEADER="Legacy BIOS"
	UEFI_STATUS="${WHITE}$(echo "LiveCD using Legacy BIOS Mode")"
else
	MODE_HEADER="UEFI"
	UEFI_STATUS="${WHITE}$(echo "LiveCD using UEFI Mode - $(sbctl status|grep "Secure" | awk '{print $1, $2}') ${GREEN}$(sbctl status|grep "Secure" | awk '{print $4}')")"
fi

fbecho
cat <<BANNER
${RED} =============== ${PURP}Funtoo LiveCD (64bit)${RED} ========= ${PURP} Boot ${MODE_HEADER} Mode ${RED} =========== ${WHITE}$(basename $(tty))${GREY}/6 ${RED}==${OFF}
                 ${WHITE}Created by the Funtoo Core Team${OFF}
                 ${PURP}https://www.funtoo.org${OFF}
$(cat $OS_LOGO_SET)
${PURP}*${RED} Configure network${GREY}: ${WHITE}nmtui${GREY}
${PURP}*${RED} Available Text Editors${WHITE}: vim${GREY}, ${WHITE}vi${GREY}, ${WHITE}nano${GREY}, ${WHITE}zile${GREY}, ${WHITE}joe
${PURP}*${RED} Available HEX Editor: ${WHITE}hexedit
${PURP}*${RED} Web browsers CLI: ${WHITE}elinks${GREY}, ${WHITE}w3m${GREY}, ${WHITE}links
${PURP}*${RED} Tools${GREY}:
    ${PURP}-${GREY} Partition manager: ${WHITE}parted${GREY}, ${WHITE}fdisk${GREY}, ${WHITE}cfdisk${GREY}, ${WHITE}gdisk${GREY}
    ${PURP}-${GREY} Diagnostic: ${WHITE}htop${GREY}, ${WHITE}whdd${GREY}, ${WHITE}hdparm${GREY}, ${WHITE}iostat${GREY}, ${WHITE}iotop${GREY}, ${WHITE}lsof${GREY}, ${WHITE}dmidecode${GREY}, ${WHITE}hwinfo${GREY}
    ${PURP}-${GREY} Forensic / Recover: ${WHITE}photorec${GREY}, ${WHITE}foremost${GREY}, ${WHITE}dcfldd${GREY}, ${WHITE}ddrescue${GREY}
    ${PURP}-${GREY} Mount NTFS disk using ntfs-3g: ${WHITE}ntfs-3g /dev/sda1 /mnt/windows${GREY}

 ${GREY}Default password for root is ${WHITE}root${GREY}. To change the root password, type: ${WHITE}passwd

${RED} ==================================================================================${OFF}

${PURP}*${RED} ${UEFI_STATUS}

${RED} ==================================================================================${OFF}

BANNER
