#!/sbin/openrc-run
# Released under the 2-clause BSD license.

description="Set up tmpfiles.d entries for /dev"

start_pre()
{
	# FL-8903:
	# Ensure / is owned by root. On existing installs, / may be owned by 1000,
	# which would result in an unsafe path transition. This is an artifact of
	# an issue with Metro, which has already been resolved.
	chown 0:0 /
}

depend()
{
	provide stmpfiles-dev stmpfiles.dev tmpfiles-dev tmpfiles.dev
	use dev-mount
	before dev
	keyword -prefix -vserver
}

start()
{
	ebegin "Setting up tmpfiles.d entries for /dev"
	/bin/systemd-tmpfiles --prefix=/dev --create --boot ${stmpfiles_opts}
	eend $?
}
